export const HANDLE_FETCH_PRODUCT_LIST = 'PRODUCTS/HANDLE_FETCH_PRODUCT_LIST';
export const HANDLE_FETCH_PRODUCT_LIST_SUCCESS =
  'PRODUCTS/HANDLE_FETCH_PRODUCT_LIST_SUCCESS';
export const HANDLE_FETCH_PRODUCT_LIST_FAIL =
  'PRODUCTS/HANDLE_FETCH_PRODUCT_LIST_FAIL';
export const HANDLE_SEARCH_PRODUCT = 'PRODUCTS/HANDLE_SEARCH_PRODUCT';
export const HANDLE_SEARCH_PRODUCT_SUCCESS =
  'PRODUCTS/HANDLE_SEARCH_PRODUCT_SUCCESS';
export const HANDLE_SEARCH_PRODUCT_FAIL = 'PRODUCTS/HANDLE_SEARCH_PRODUCT_FAIL';
export const HANDLE_FETCH_CATEGORIES = 'PRODUCTS/HANDLE_FETCH_CATEGORIES';
export const HANDLE_FETCH_CATEGORIES_FAIL =
  'PRODUCTS/HANDLE_FETCH_CATEGORIES_FAIL';
export const HANDLE_FETCH_CATEGORIES_SUCCESS =
  'PRODUCTS/HANDLE_FETCH_CATEGORIES_SUCCESS';
export const HANDLE_SELECT_FILTER_CATEGORIES =
  'PRODUCTS/HANDLE_SELECT_FILTER_CATEGORIES';
export const HANDLE_APPLY_FILTERS = 'PRODUCTS/HANDLE_APPLY_FILTERS';
export const HANDLE_APPLY_FILTERS_SUCCESS =
  'PRODUCTS/HANDLE_APPLY_FILTERS_SUCCESS';
export const HANDLE_APPLY_FILTERS_FAIL = 'PRODUCTS/HANDLE_APPLY_FILTERS_FAIL';
