export const HANDLE_FETCH_PRODUCT_LIST = 'PRODUCTS/HANDLE_FETCH_PRODUCT_LIST';
export const HANDLE_FETCH_PRODUCT_LIST_SUCCESS =
  'PRODUCTS/HANDLE_FETCH_PRODUCT_LIST_SUCCESS';
export const HANDLE_FETCH_PRODUCT_LIST_FAIL =
  'PRODUCTS/HANDLE_FETCH_PRODUCT_LIST_FAIL';
export const HANDLE_SEARCH_PRODUCT = 'PRODUCTS/HANDLE_SEARCH_PRODUCT';
export const HANDLE_SEARCH_PRODUCT_SUCCESS =
  'PRODUCTS/HANDLE_SEARCH_PRODUCT_SUCCESS';
export const HANDLE_SEARCH_PRODUCT_FAIL = 'PRODUCTS/HANDLE_SEARCH_PRODUCT_FAIL';
