export const HANDLE_FETCH_PRODUCT_LIST = 'PRODUCTS/HANDLE_FETCH_PRODUCT_LIST';
export const HANDLE_FETCH_PRODUCT_LIST_SUCCESS =
  'PRODUCTS/HANDLE_FETCH_PRODUCT_LIST_SUCCESS';
export const HANDLE_FETCH_PRODUCT_LIST_FAIL =
  'PRODUCTS/HANDLE_FETCH_PRODUCT_LIST_FAIL';
