// export const HANDLE_FETCH_WAREHOUSE_ITEMS = 'WAREHOUSE/FETCH_WAREHOUSE_ITEMS';
// export const HANDLE_FETCH_WAREHOUSE_ITEMS_FAIL =
//   'WAREHOUSE/FETCH_WAREHOUSE_ITEMS_FAIL';
// export const HANDLE_FETCH_WAREHOUSE_ITEMS_SUCCESS =
//   'WAREHOUSE/FETCH_WAREHOUSE_ITEMS_SUCCESS';
// export const HANDLE_SET_LIMIT = 'WAREHOUSE/SET_LIMIT';
// export const HANDLE_SET_PAGE = 'WAREHOUSE/SET_PAGE';
// export const HANDLE_SET_SEARCH_FOR_NAME = 'WAREHOUSE/SET_SEARCHFORNAME';
