export const HANDLE_CHANGE_TAB_DISPLAY = 'WAREHOUSE_TICKET/CHANGE_TAB_DISPLAY';
export const HANDLE_FETCH_WAREHOUSE_TRANSACTION =
  'WAREHOUSE_TICKET/FETCH_WAREHOUSE_TRANSACTION';
export const HANDLE_FETCH_WAREHOUSE_TRANSACTION_SUCCESS =
  'WAREHOUSE_TICKET/FETCH_WAREHOUSE_TRANSACTION_SUCCESS';
export const HANDLE_FETCH_WAREHOUSE_TRANSACTION_FAIL =
  'WAREHOUSE_TICKET/FETCH_WAREHOUSE_TRANSACTION_FAIL';

export const HANDLE_FETCH_DETAIL_WAREHOUSE_TRANSACTION =
  'WAREHOUSE_TICKET/FETCH_DETAIL_WAREHOUSE_TRANSACTION';
export const HANDLE_FETCH_DETAIL_WAREHOUSE_TRANSACTION_SUCCESS =
  'WAREHOUSE_TICKET/FETCH_DETAIL_WAREHOUSE_TRANSACTION_SUCCESS';
export const HANDLE_FETCH_DETAIL_WAREHOUSE_TRANSACTION_FAIL =
  'WAREHOUSE_TICKET/FETCH_DETAIL_WAREHOUSE_TRANSACTION_FAIL';

export const HANDLE_SET_LIMIT = 'WAREHOUSE_TICKET/SET_LIMIT';
export const HANDLE_SET_PAGE = 'WAREHOUSE_TICKET/SET_PAGE';
export const HANDLE_SET_SEARCH_FOR_NAME = 'WAREHOUSE_TICKET/SET_SEARCHFORNAME';
export const HANDLE_CLEAR_MANUFACTURERS =
  'WAREHOUSE_TICKET/CLEAR_MANUFACTURERS';
export const HANDLE_FETCH_MANUFACTURERS =
  'WAREHOUSE_TICKET/FETCH_MANUFACTURERS';
export const HANDLE_FETCH_MANUFACTURERS_SUCCESS =
  'WAREHOUSE_TICKET/FETCH_MANUFACTURERS_SUCCESS';
export const HANDLE_FETCH_MANUFACTURERS_FAIL =
  'WAREHOUSE_TICKET/FETCH_MANUFACTURERS_FAIL';
export const HANDLE_SELECT_MANUFACTURER =
  'WAREHOUSE_TICKET/SELECT_MANUFACTURER';

export const HANDLE_CLEAR_PRODUCTS = 'WAREHOUSE_TICKET/CLEAR_PRODUCTS';
export const HANDLE_FETCH_PRODUCTS = 'WAREHOUSE_TICKET/FETCH_PRODUCTS';
export const HANDLE_FETCH_PRODUCTS_SUCCESS =
  'WAREHOUSE_TICKET/FETCH_PRODUCTS_SUCCESS';
export const HANDLE_FETCH_PRODUCTS_FAIL =
  'WAREHOUSE_TICKET/FETCH_PRODUCTS_FAIL';
export const HANDLE_SELECT_PRODUCT = 'WAREHOUSE_TICKET/SELECT_PRODUCT';
export const HANDLE_CHANGE_ITEM_QUANTITY =
  'WAREHOUSE_TICKET/HANDLE_CHANGE_ITEM_QUANTITY';
export const HANDLE_DELETE_ITEM = 'WAREHOUSE_TICKET/HANDLE_DELETE_ITEM';
export const HANDLE_CLEAR_NEW_DATA = 'WAREHOUSE_TICKET/HANDLE_CLEAR_DATA';
export const HANDLE_CREATE_NEW_WAREHOUSE_TRANSACTION =
  'WAREHOUSE_TICKET/HANDLE_CREATE_NEW_WAREHOUSE_TRANSACTION';
export const HANDLE_CREATE_NEW_WAREHOUSE_TRANSACTION_SUCCESS =
  'WAREHOUSE_TICKET/HANDLE_CREATE_NEW_WAREHOUSE_TRANSACTION_SUCCESS';
export const HANDLE_CREATE_NEW_WAREHOUSE_TRANSACTION_FAIL =
  'WAREHOUSE_TICKET/HANDLE_CREATE_NEW_WAREHOUSE_TRANSACTION_FAIL';
export const HANDLE_CHANGE_DESCRIPTION =
  'WAREHOUSE_TICKET/HANDLE_CHANGE_DESCRIPTION';
export const HANDLE_CHANGE_ITEM_COST =
  'WAREHOUSE_TICKET/HANDLE_CHANGE_ITEM_COST';

export const HANDLE_CONFIRM_WAREHOUSE_TRANSACTION =
  'WAREHOUSE_TICKET/HANDLE_CONFIRM_WAREHOUSE_TRANSACTION';
export const HANDLE_CONFIRM_WAREHOUSE_TRANSACTION_SUCCESS =
  'WAREHOUSE_TICKET/HANDLE_CONFIRM_WAREHOUSE_TRANSACTION_SUCCESS';
export const HANDLE_CONFIRM_WAREHOUSE_TRANSACTION_FAIL =
  'WAREHOUSE_TICKET/HANDLE_CONFIRM_WAREHOUSE_TRANSACTION_FAIL';

export const HANDLE_CANCEL_WAREHOUSE_TRANSACTION =
  'WAREHOUSE_TICKET/HANDLE_CANCEL_WAREHOUSE_TRANSACTION';
export const HANDLE_CANCEL_WAREHOUSE_TRANSACTION_SUCCESS =
  'WAREHOUSE_TICKET/HANDLE_CANCEL_WAREHOUSE_TRANSACTION_SUCCESS';
export const HANDLE_CANCEL_WAREHOUSE_TRANSACTION_FAIL =
  'WAREHOUSE_TICKET/HANDLE_CANCEL_WAREHOUSE_TRANSACTION_FAIL';
