export const HANDLE_CHANGE_TAB_DISPLAY = 'WAREHOUSE_TICKET/CHANGE_TAB_DISPLAY';
export const HANDLE_FETCH_WAREHOUSE_TRANSACTION =
  'WAREHOUSE_TICKET/FETCH_WAREHOUSE_TRANSACTION';
export const HANDLE_FETCH_WAREHOUSE_TRANSACTION_SUCCESS =
  'WAREHOUSE_TICKET/FETCH_WAREHOUSE_TRANSACTION_SUCCESS';
export const HANDLE_FETCH_WAREHOUSE_TRANSACTION_FAIL =
  'WAREHOUSE_TICKET/FETCH_WAREHOUSE_TRANSACTION_FAIL';

export const HANDLE_SET_LIMIT = 'MANUFACTURER/SET_LIMIT';
export const HANDLE_SET_PAGE = 'MANUFACTURER/SET_PAGE';
export const HANDLE_SET_SEARCH_FOR_NAME = 'MANUFACTURER/SET_SEARCHFORNAME';
