export const HANDLE_LOGIN_EMAIL = 'AUTH/HANDLE_LOGIN_EMAIL';
export const HANDLE_LOGIN_EMAIL_SUCCESS = 'AUTH/HANDLE_LOGIN_EMAIL_SUCCESS';
export const HANDLE_LOGIN_EMAIL_FAIL = 'AUTH/HANDLE_LOGIN_EMAIL_FAIL';
export const HANDLE_CLOSE_SNACKBAR = 'AUTH/HANDLE_CLOSE_SNACKBAR';
export const HANDLE_LOGOUT = 'AUTH/HANDLE_LOGOUT';
