export const HANDLE_FETCH_USER_INFO = 'ACCOUNT/HANDLE_FETCH_USER_INFO';
export const HANDLE_FETCH_USER_INFO_SUCCESS =
  'ACCOUNT/HANDLE_FETCH_USER_INFO_SUCCESS';
export const HANDLE_FETCH_USER_INFO_FAIL =
  'ACCOUNT/HANDLE_FETCH_USER_INFO_FAIL';
export const HANDLE_UPDATE_USER_INFO = 'ACCOUNT/HANDLE_UPDATE_USER_INFO';
export const HANDLE_UPDATE_USER_INFO_SUCCESS =
  'ACCOUNT/HANDLE_UPDATE_USER_INFO_SUCCESS';
export const HANDLE_UPDATE_USER_INFO_FAIL =
  'ACCOUNT/HANDLE_UPDATE_USER_INFO_FAIL';
export const HANDLE_CLOSE_SNACKBAR = 'ACCOUNT/CLOSE_SNACKBAR';
export const HANDLE_UPLOAD_IMAGE = 'ACCOUNT/UPLOAD_IMAGE';
export const HANDLE_UPLOAD_IMAGE_FAIL = 'ACCOUNT/UPLOAD_IMAGE_FAIL';
export const HANDLE_UPLOAD_IMAGE_SUCCESS = 'ACCOUNT/UPLOAD_IMAGE_SUCCESS';
export const HANDLE_UPDATE_PASSWORD = 'ACCOUNT/UPDATE_PASSWORD';
export const HANDLE_UPDATE_PASSWORD_FAIL = 'ACCOUNT/UPDATE_PASSWORD_FAIL';
export const HANDLE_UPDATE_PASSWORD_SUCCESS = 'ACCOUNT/UPDATE_PASSWORD_SUCCESS';
