export const HANDLE_FETCH_USER_INFO = 'ACCOUNT/HANDLE_FETCH_USER_INFO';
export const HANDLE_FETCH_USER_INFO_SUCCESS =
  'ACCOUNT/HANDLE_FETCH_USER_INFO_SUCCESS';
export const HANDLE_FETCH_USER_INFO_FAIL =
  'ACCOUNT/HANDLE_FETCH_USER_INFO_FAIL';
export const HANDLE_UPDATE_USER_INFO = 'ACCOUNT/HANDLE_UPDATE_USER_INFO';
export const HANDLE_UPDATE_USER_INFO_SUCCESS =
  'ACCOUNT/HANDLE_UPDATE_USER_INFO_SUCCESS';
export const HANDLE_UPDATE_USER_INFO_FAIL =
  'ACCOUNT/HANDLE_UPDATE_USER_INFO_FAIL';
