export const HANDLE_FETCH_MANUFACTURER = 'MANUFACTURER/FETCH_MANUFACTURER';
export const HANDLE_FETCH_MANUFACTURER_FAIL =
  'MANUFACTURER/FETCH_MANUFACTURER_FAIL';
export const HANDLE_FETCH_MANUFACTURER_SUCCESS =
  'MANUFACTURER/FETCH_MANUFACTURER_SUCCESS';
export const HANDLE_SET_LIMIT = 'MANUFACTURER/SET_LIMIT';
export const HANDLE_SET_PAGE = 'MANUFACTURER/SET_PAGE';
export const HANDLE_SET_SEARCH_FOR_NAME = 'MANUFACTURER/SET_SEARCHFORNAME';
export const HANDLE_SHOW_MANUFACTURER_INFO =
  'MANUFACTURER/SHOW_MANUFACTURER_INFO';
export const HANDLE_GET_ALL_PROVINCES = 'MANUFACTURER/GET_ALL_PROVINCES';
export const HANDLE_GET_ALL_PROVINCES_SUCCESS =
  'MANUFACTURER/GET_ALL_PROVINCES_SUCCESS';
export const HANDLE_GET_ALL_PROVINCES_FAIL =
  'MANUFACTURER/GET_ALL_PROVINCES_FAIL';

export const HANDLE_GET_ALL_DISTRICTS = 'MANUFACTURER/GET_ALL_DISTRICTS';
export const HANDLE_GET_ALL_DISTRICTS_SUCCESS =
  'MANUFACTURER/GET_ALL_DISTRICTS_SUCCESS';
export const HANDLE_GET_ALL_DISTRICTS_FAIL =
  'MANUFACTURER/GET_ALL_DISTRICTS_FAIL';

export const HANDLE_GET_ALL_WARDS = 'MANUFACTURER/GET_ALL_WARDS';
export const HANDLE_GET_ALL_WARDS_SUCCESS =
  'MANUFACTURER/GET_ALL_WARDS_SUCCESS';
export const HANDLE_GET_ALL_WARDS_FAIL = 'MANUFACTURER/GET_ALL_WARDS_FAIL';
export const HANDLE_CHANGE_WARD = 'MANUFACTURER/CHANGE_WARD';
export const HANDLE_CHANGE_MANUFACTURER_INFO =
  'MANUFACTURER/CHANGE_MANUFACTURER_INFO';
export const HANDLE_SAVE_UPDATE_MANUFACTURER_INFO =
  'MANUFACTURER/SAVE_UPDATE_MANUFACTURER_INFO';
export const HANDLE_SAVE_UPDATE_MANUFACTURER_INFO_SUCCESS =
  'MANUFACTURER/SAVE_UPDATE_MANUFACTURER_INFO_SUCCESS';
export const HANDLE_SAVE_UPDATE_MANUFACTURER_INFO_FAIL =
  'MANUFACTURER/SAVE_UPDATE_MANUFACTURER_INFO_FAIL';
export const HANDLE_CLOSE_SNACKBAR = 'MANUFACTURER/CLOSE_SNACKBAR';

export const HANDLE_GET_DETAIL_MANUFACTURER =
  'MANUFACTURER/GET_DETAIL_MANUFACTURER';
export const HANDLE_GET_DETAIL_MANUFACTURER_SUCCESS =
  'MANUFACTURER/GET_DETAIL_MANUFACTURER_SUCCESS';
export const HANDLE_GET_DETAIL_MANUFACTURER_FAIL =
  'MANUFACTURER/GET_DETAIL_MANUFACTURER_FAIL';

export const HANDLE_DELETE_MANUFACTURER = 'MANUFACTURER/DELETE_MANUFACTURER';

export const HANDLE_DELETE_MANUFACTURER_FAIL =
  'MANUFACTURER/DELETE_MANUFACTURER_FAIL';

export const HANDLE_DELETE_MANUFACTURER_SUCCESS =
  'MANUFACTURER/DELETE_MANUFACTURER_SUCCESS';
