export const HANDLE_FETCH_MANUFACTURER = 'MANUFACTURER/FETCH_MANUFACTURER';
export const HANDLE_FETCH_MANUFACTURER_FAIL =
  'MANUFACTURER/FETCH_MANUFACTURER_FAIL';
export const HANDLE_FETCH_MANUFACTURER_SUCCESS =
  'MANUFACTURER/FETCH_MANUFACTURER_SUCCESS';
export const HANDLE_SET_LIMIT = 'MANUFACTURER/SET_LIMIT';
export const HANDLE_SET_PAGE = 'MANUFACTURER/SET_PAGE';
export const HANDLE_SET_SEARCH_FOR_NAME = 'MANUFACTURER/SET_SEARCHFORNAME';
