export const HANDLE_FETCH_PRODUCT_DETAIL =
  'PRODUCTS/HANDLE_FETCH_PRODUCT_DETAIL';
export const HANDLE_FETCH_PRODUCT_DETAIL_SUCCESS =
  'PRODUCTS/HANDLE_FETCH_PRODUCT_DETAIL_SUCCESS';
export const HANDLE_FETCH_PRODUCT_DETAIL_FAIL =
  'PRODUCTS/HANDLE_FETCH_PRODUCT_DETAIL_FAIL';
export const HANDLE_REMOVE_PRODUCT_IMAGE =
  'PRODUCTS/HANDLE_REMOVE_PRODUCT_IMAGE';
export const HANDLE_UPLOAD_PRODUCT_IMAGES =
  'PRODUCTS/HANDLE_UPLOAD_PRODUCT_IMAGES';
export const HANDLE_UPLOAD_PRODUCT_IMAGES_SUCCESS =
  'PRODUCTS/HANDLE_UPLOAD_PRODUCT_IMAGES_SUCCESS';
export const HANDLE_UPLOAD_PRODUCT_IMAGES_FAIL =
  'PRODUCTS/HANDLE_UPLOAD_PRODUCT_IMAGES_FAIL';
