export const HANDLE_FETCH_PRODUCT_DETAIL =
  'PRODUCTS/HANDLE_FETCH_PRODUCT_DETAIL';
export const HANDLE_FETCH_PRODUCT_DETAIL_SUCCESS =
  'PRODUCTS/HANDLE_FETCH_PRODUCT_DETAIL_SUCCESS';
export const HANDLE_FETCH_PRODUCT_DETAIL_FAIL =
  'PRODUCTS/HANDLE_FETCH_PRODUCT_DETAIL_FAIL';
