export const HANDLE_FETCH_WAREHOUSE_ITEMS = 'WAREHOUSE/FETCH_WAREHOUSE_ITEMS';
export const HANDLE_FETCH_WAREHOUSE_ITEMS_FAIL =
  'WAREHOUSE/FETCH_WAREHOUSE_ITEMS_FAIL';
export const HANDLE_FETCH_WAREHOUSE_ITEMS_SUCCESS =
  'WAREHOUSE/FETCH_WAREHOUSE_ITEMS_SUCCESS';
