export const HANDLE_FETCH_CART = 'CART/FETCH_CART';
export const HANDLE_FETCH_CART_SUCCESS = 'CART/FETCH_CART_SUCCESS';
export const HANDLE_FETCH_CART_FAIL = 'CART/FETCH_CART_FAIL';
export const HANDLE_SET_LIMIT = 'MANUFACTURER/SET_LIMIT';
export const HANDLE_SET_PAGE = 'MANUFACTURER/SET_PAGE';
