export const HANDLE_FETCH_CART = 'CART/FETCH_CART';
export const HANDLE_FETCH_CART_SUCCESS = 'CART/FETCH_CART_SUCCESS';
export const HANDLE_FETCH_CART_FAIL = 'CART/FETCH_CART_FAIL';

export const HANDLE_FETCH_CART_SINGLE = 'CART/FETCH_CART_SINGLE';
export const HANDLE_FETCH_CART_SINGLE_SUCCESS =
  'CART/FETCH_CART_SINGLE_SUCCESS';
export const HANDLE_FETCH_CART_SINGLE_FAIL = 'CART/FETCH_CART_SINGLE_FAIL';

export const HANDLE_SET_LIMIT = 'CART/SET_LIMIT';
export const HANDLE_SET_PAGE = 'CART/SET_PAGE';
export const HANDLE_UPDATE_STATUS = 'CART/UPDATE_STATUS';
export const HANDLE_UPDATE_STATUS_FAIL = 'CART/UPDATE_STATUS_FAIL';
export const HANDLE_UPDATE_STATUS_SUCCESS = 'CART/UPDATE_STATUS_SUCCESS';
export const HANDLE_CLOSE_SNACKBAR = 'CART/CLOSE_SNACKBAR';
