export const HANDLE_FETCH_PRODUCT_DETAIL =
  'PRODUCTS/NEW/HANDLE_FETCH_PRODUCT_DETAIL';
export const HANDLE_FETCH_PRODUCT_DETAIL_SUCCESS =
  'PRODUCTS/NEW/HANDLE_FETCH_PRODUCT_DETAIL_SUCCESS';
export const HANDLE_FETCH_PRODUCT_DETAIL_FAIL =
  'PRODUCTS/NEW/HANDLE_FETCH_PRODUCT_DETAIL_FAIL';
export const HANDLE_REMOVE_PRODUCT_IMAGE =
  'PRODUCTS/NEW/HANDLE_REMOVE_PRODUCT_IMAGE';
export const HANDLE_UPLOAD_PRODUCT_IMAGES =
  'PRODUCTS/NEW/HANDLE_UPLOAD_PRODUCT_IMAGES';
export const HANDLE_UPLOAD_PRODUCT_IMAGES_SUCCESS =
  'PRODUCTS/NEW/HANDLE_UPLOAD_PRODUCT_IMAGES_SUCCESS';
export const HANDLE_UPLOAD_PRODUCT_IMAGES_FAIL =
  'PRODUCTS/NEW/HANDLE_UPLOAD_PRODUCT_IMAGES_FAIL';
export const HANDLE_FETCH_CATEGORIES = 'PRODUCTS/NEW/HANDLE_FETCH_CATEGORIES';
export const HANDLE_FETCH_CATEGORIES_SUCCESS =
  'PRODUCTS/NEW/HANDLE_FETCH_CATEGORIES_SUCCESS';
export const HANDLE_FETCH_CATEGORIES_FAIL =
  'PRODUCTS/NEW/HANDLE_FETCH_CATEGORIES_FAIL';
export const HANDLE_SELECT_CATEGORY = 'PRODUCTS/NEW/HANDLE_SELECT_CATEGORY';
export const HANDLE_CHANGE_STATUS = 'PRODUCTS/NEW/HANDLE_CHANGE_STATUS';

export const HANDLE_CHANGE_DESCRIPTION =
  'PRODUCTS/NEW/HANDLE_CHANGE_DESCRIPTION';
export const HANDLE_CHANGE_NAME = 'PRODUCTS/NEW/HANDLE_CHANGE_NAME';
export const HANDLE_CHANGE_PRICE = 'PRODUCTS/NEW/HANDLE_CHANGE_PRICE';
export const HANDLE_CHANGE_COST = 'PRODUCTS/NEW/HANDLE_CHANGE_COST';
export const HANDLE_CHANGE_QUANTITY = 'PRODUCTS/NEW/HANDLE_CHANGE_QUANTITY';
export const HANDLE_CHANGE_MANAGE_VARIANT =
  'PRODUCTS/NEW/HANDLE_CHANGE_MANAGE_VARIANT';

export const HANDLE_ADD_NEW_VARIANT = 'PRODUCTS/NEW/HANDLE_ADD_NEW_VARIANT';
export const HANDLE_DELETE_VARIANT = 'PRODUCTS/NEW/HANDLE_DELETE_VARIANT';

export const HANDLE_CHANGE_VARIANT_PROPERTY =
  'PRODUCTS/NEW/VARIANTS/HANDLE_CHANGE_PROPERTY';

export const HANDLE_ADD_PRODUCT = 'PRODUCTS/NEW/HANDLE_ADD_PRODUCT';
export const HANDLE_ADD_PRODUCT_SUCCESS =
  'PRODUCTS/NEW/HANDLE_ADD_PRODUCT_SUCCESS';
export const HANDLE_ADD_PRODUCT_FAIL = 'PRODUCTS/NEW/HANDLE_ADD_PRODUCT_FAIL';

export const HANDLE_DELETE_PRODUCT = 'PRODUCTS/NEW/HANDLE_DELETE_PRODUCT';
export const HANDLE_DELETE_PRODUCT_SUCCESS =
  'PRODUCTS/NEW/HANDLE_DELETE_PRODUCT_SUCCESS';
export const HANDLE_DELETE_PRODUCT_FAIL =
  'PRODUCTS/NEW/HANDLE_DELETE_PRODUCT_FAIL';
export const HANDLE_CLEAR_PRODUCT_DATA =
  'PRODUCTS/NEW/HANDLE_CLEAR_PRODUCT_DATA';
export const HANDLE_CREATE_CATEGORY = 'PRODUCTS/HANDLE_CREATE_CATEGORY';
export const HANDLE_CREATE_CATEGORY_SUCCESS =
  'PRODUCTS/HANDLE_CREATE_CATEGORY_SUCCESS';
export const HANDLE_CREATE_CATEGORY_FAIL =
  'PRODUCTS/HANDLE_CREATE_CATEGORY_FAIL';
export const HANDLE_CHANGE_DIMENSION = 'PRODUCTS/HANDLE_CHANGE_DIMENSION';
export const HANDLE_CHANGE_TAGS = 'PRODUCTS/HANDLE_CHANGE_TAGS';
export const HANDLE_CREATE_FEATURE = 'PRODUCTS/HANDLE_CREATE_FEATURE';
export const HANDLE_CHANGE_FEATURE = 'PRODUCTS/HANDLE_CHANGE_FEATURE';
export const HANDLE_REMOVE_FEATURE = 'PRODUCTS/HANDLE_REMOVE_FEATURE';
export const HANDLE_TOGGLE_PRODUCT_DISCOUNT =
  'PRODUCTS/TOGGLE_PRODUCT_DISCOUNT';
export const HANDLE_CHANGE_PRODUCT_DISCOUNT =
  'PRODUCTS/CHANGE_PRODUCT_DISCOUNT';
